# Preparación: Nuestras 3 tablitas de Lego

In [1]:
import pandas as pd

# Tabla 1: Ventas de Enero
df_enero = pd.DataFrame({
    'id_venta': ['V-01', 'V-02'],
    'id_producto': [101, 102],
    'cantidad': [1, 2]
})

# Tabla 2: Ventas de Febrero (Nota que alguien compró el producto 999, ¡que no existe!)
df_febrero = pd.DataFrame({
    'id_venta': ['V-03', 'V-04'],
    'id_producto': [101, 999],
    'cantidad': [1, 5]
})

# Tabla 3: Nuestro Catálogo (El "Diccionario")
df_catalogo = pd.DataFrame({
    'id_producto': [101, 102, 103],
    'nombre_prod': ['Laptop', 'Mouse', 'Teclado'],
    'precio': [1000, 25, 45]
})

print("--- VENTAS ENERO ---")
print(df_enero)
print("\n--- CATÁLOGO ---")
print(df_catalogo)

--- VENTAS ENERO ---
  id_venta  id_producto  cantidad
0     V-01          101         1
1     V-02          102         2

--- CATÁLOGO ---
   id_producto nombre_prod  precio
0          101      Laptop    1000
1          102       Mouse      25
2          103     Teclado      45


# Ejemplo 1: pd.concat() (El Apilador de Documentos)

El Problema: Tu jefe te dice: "No quiero ver enero y febrero separados, dame una sola tabla con todas las ventas del año".
La Solución: Apilarlas una debajo de la otra. Como tienen las mismas columnas, encajan perfecto.

In [2]:
# Pasamos una lista de DataFrames dentro de corchetes [ ]
df_ventas_totales = pd.concat([df_enero,df_febrero])

print("---- Todas las ventas-----")
print(df_ventas_totales)

---- Todas las ventas-----
  id_venta  id_producto  cantidad
0     V-01          101         1
1     V-02          102         2
0     V-03          101         1
1     V-04          999         5


¿Qué pasó? Pandas simplemente tomó la tabla de febrero y la pegó justo debajo de la de enero. Ahora tienes 4 filas. No buscó coincidencias, solo apiló.

# Ejemplo 2: pd.merge() con how='left' (El Buscador V)

El Problema: Tienes tu tabla df_ventas_totales (4 ventas). Pero solo tienes el id_producto. Si le pasas eso a tu jefe, te dirá: "¿Qué diablos es el producto 101?". Necesitas traer el nombre y el precio desde el df_catalogo.

Aquí entra el Left Join (El más usado en el mundo laboral).

In [3]:
# df_ventas_totales es la izquierda (left). df_catalogo es la derecha (Rigth).
# 'on' es la columna puente (la llave) que existe en ambas
df_reporte_left = pd.merge(df_ventas_totales,df_catalogo,on='id_producto',how='left')

print("--- REPORTE CON NOMBRES (LEFT JOIN) ---")
print(df_reporte_left)

--- REPORTE CON NOMBRES (LEFT JOIN) ---
  id_venta  id_producto  cantidad nombre_prod  precio
0     V-01          101         1      Laptop  1000.0
1     V-02          102         2       Mouse    25.0
2     V-03          101         1      Laptop  1000.0
3     V-04          999         5         NaN     NaN


Analicemos la magia paso a paso:

    Pandas tomó la venta V-01 (producto 101). Fue al catálogo, buscó el 101, vio que era "Laptop" y lo pegó al lado.

    Mira la Venta V-04 (Producto 999): Pandas fue al catálogo a buscar el 999... y no lo encontró.

    ¿Qué hizo el Left Join? Como le dijimos que la tabla Izquierda (ventas_totales) es la intocable, mantuvo la venta V-04, pero le puso NaN (Nulo) en el nombre y precio. ¡No perdimos la venta!

# Ejemplo 3: pd.merge() con how='inner' (El Club Exclusivo)

El Problema: Finanzas quiere un reporte perfecto. Te dicen: "Si un producto no está en el catálogo oficial, no lo incluyas en este cálculo porque nos daña la contabilidad".

Aquí usamos el Inner Join. Exige que el dato exista en AMBAS tablas para sobrevivir.

In [4]:
df_reporte_inner = pd.merge(df_ventas_totales,df_catalogo,on='id_producto',how='inner')

print("---  REPORTE ESTRICTO (INNER JOIN) ---")
print(df_reporte_inner)

---  REPORTE ESTRICTO (INNER JOIN) ---
  id_venta  id_producto  cantidad nombre_prod  precio
0     V-01          101         1      Laptop    1000
1     V-02          102         2       Mouse      25
2     V-03          101         1      Laptop    1000


¿Qué pasó aquí?
¡La venta V-04 desapareció del universo!
Como el producto 999 no estaba en el catálogo, el Inner Join dijo: "No hay coincidencia perfecta, elimino toda la fila de la venta".